---
- name: Create VPC attachment
  community.aws.ec2_transit_gateway_vpc_attachment:
    state: present
    name: "{{ item.name }}"
    transit_gateway: "{{ manage_transit_gateway_tgw_result.transit_gateway.transit_gateway_id }}"
    subnets: "{{ item.subnets }}"
    tags: "{{ item.tags }}"
    purge_subnets: False
  register: manage_transit_gateway_tgw_vpc_attachment_result

- name: Verify that the transit gateway vpc attachment has been successfully created.
  ansible.builtin.debug:
    msg: Transit gateway VPC attachment {{ item.name }} has been successfully created.
  when: manage_transit_gateway_tgw_vpc_attachment_result is changed

- name: Print debug message
  ansible.builtin.debug:
    msg: Transit gateway VPC attachment {{ item.name }} already exists with the given subnets.
  when: manage_transit_gateway_tgw_vpc_attachment_result is not changed
